### ISSUE TITLE
Возможность выбора взаимоисключающих параметров

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#16]
В форме добавления маски присутствует возможность выбрать взаимоисключающие варианты (и да и нет) в   чекбоксах и всё сохранится
![2018-01-10_170245](https://user-images.githubusercontent.com/30126152/34780110-de44e2e0-f62a-11e7-8130-b0d584f90a6e.jpg)

--

**Comment by konstcos** [comment]
Это не ошибка, форма маски у агента так и должна работать.
