### ISSUE TITLE
Новый лид у всех пользователей

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#22]
После создания аккаунт менеджером агента, неважно Lead   Byer или Deal Maker, у агента после входа в систему появляется возможность создавать новый лид. При регистрации агента без аккаунт менеджера такой возможности не было.
![screenshot-2018-1-11 contact](https://user-images.githubusercontent.com/30126152/34820177-7629b7e6-f6c8-11e7-943a-1cce0f2f19ef.png)

**Comment by konstcos** [comment]
это потому что после самостоятельной регистрации агент ждет пока его подберет акк. менеджер. В случае регистрации менеджером, у агента уже есть менеджер, поэтому он сразу может вносить лиды.
Слава, подтверди.

**Comment by VyacheslavZemko** [comment]
Да, все верно. Подтверждаю
