### ISSUE TITLE
Email добавляется без проверки

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#23]
Email может быть любым, проходящим валидацию. Проверки, как в случае самостоятельной регистрации агента не происходит.
![2018-01-11_134853](https://user-images.githubusercontent.com/30126152/34824344-c2bcd6e8-f6d6-11e7-87c3-b9625ba671c2.jpg)

**Comment by konstcos** [comment]
ты имеешь в виду подтверждение мэила по почте?

**Comment by strannik-mas** [comment]
да, получается что можно аккаунт менеджер может добавить несуществующий мэйл

**Comment by konstcos** [comment]
В таких случаях подтверждение мэила не делается, а стоило бы ...думаю завтра этот момент как раз и обсудим
