### ISSUE TITLE
Повторное всплытие модального окна в Firefox

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#25]
Только в Firefox при открытии оператором на редактирование лида в статусе " Оператор" всплывает модальное окно с подтверждением, после согласия переходим на редактирование. Теперь на этой странице если нажать браузерную кнопку "Back", то это окно всплывёт снова.
![screenshot-2018-1-12 contact](https://user-images.githubusercontent.com/30126152/34867796-21f089c6-f78a-11e7-8759-3c7bbb17b797.png)
![2018-01-12_111043](https://user-images.githubusercontent.com/30126152/34867799-243f6bd4-f78a-11e7-9b5a-972f007d6f7a.jpg)

**Comment by konstcos** [comment]
нужно просмотреть и подумать почему такое происходит
