### ISSUE TITLE
Бесплатные лиды

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#29]
Если агент создал маску и она в статусе "approve vating", то он может открыть лид, попавший по фильтрам в эту маску.
![2018-01-12_160600](https://user-images.githubusercontent.com/30126152/34878524-18d7437e-f7b3-11e7-9691-b7f7d50c7d8c.jpg)
![2018-01-12_160619](https://user-images.githubusercontent.com/30126152/34878529-1c903ce6-f7b3-11e7-854a-d4a5759a88a5.jpg)
![2018-01-12_160712](https://user-images.githubusercontent.com/30126152/34878531-1f2566fc-f7b3-11e7-8bf6-81cf03ebf571.jpg)

**Comment by konstcos** [comment]
У меня такое повторить не получилось...
Саша, скинь данные самого агента и депозитора, который вносил лиды.
