### ISSUE TITLE
Ошибка сервера при редактировании масок агентов админом

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#32]
Происходит ошибка сервера при редактировании масок агентов админом
![2018-01-12_180150](https://user-images.githubusercontent.com/30126152/34883707-07c0dd6a-f7c3-11e7-845b-ef084b6e1587.jpg)
![2018-01-12_180305](https://user-images.githubusercontent.com/30126152/34883711-0b62a156-f7c3-11e7-92e0-4db54c758024.jpg)
![2018-01-12_180309](https://user-images.githubusercontent.com/30126152/34883714-0d54ea8c-f7c3-11e7-975e-df44786dff7e.jpg)

**Comment by konstcos** [comment]
Судя по всему не подтягивает кошелек акк. менеджера

![screenshot from 2018-01-14 13-32-39](https://user-images.githubusercontent.com/17494831/34915406-cb5e5aec-f92e-11e7-877b-e7dc5be0a5fd.png)
