### ISSUE TITLE
Ошибка при загрузке страницы ввода пароля в application

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#33]
Android 7.1
Процесс: аутентификация 
При входе в приложение возникает ошибка еще до ввода логина и пароля
![virtualbox_android 7 1_15_01_2018_14_46_23](https://user-images.githubusercontent.com/30126152/34944008-98b13906-fa06-11e7-99e5-359270e364f8.png)

**Comment by konstcos** [comment]
ошибка не понятная, на андроиде все устанавливается нормально (android 5.1).
Еще поганяем эту ошибку

**Comment by strannik-mas** [comment]
при перезапуске эта ошибка появляется вновь

**Comment by strannik-mas** [comment]
Но на Android 6.0 её тоже нет

**Comment by VyacheslavZemko** [comment]
У меня андроид 7.0, такой ошибки не возникает. Обращаю внимание, что у меня версия 7.0, а не 7.1

**Comment by konstcos** [comment]
Android 7.1 вышел относительно не давно. 
Думаю что эта проблема скоро решится.
От нас тут ничего не зависит...
