### ISSUE TITLE
Регистрация агента под различными мэилами

### ISSUE THREAD

**Issue by konstcos** [konstcos/contact#35]

**Comment by strannik-mas** [comment]
Андроид 7.1
Процесс: регистрация агента - ввод email/password
теперь валидация проходит, но форма не отправляется - после нажатия на кнопку остаёмся на той же странице.
![virtualbox_android 7 1_15_01_2018_17_44_13](https://user-images.githubusercontent.com/30126152/34950738-b3ef963e-fa1c-11e7-8dff-2233d97f8a04.png)

**Comment by strannik-mas** [comment]
мэйлы : test_12@amail.club
  test_12@mail2.space

**Comment by strannik-mas** [comment]
под Android 6.0 тоже самое

**Comment by strannik-mas** [comment]
всё работает хорошо
