### ISSUE TITLE
Невозможно войти в веб версию при регистрации на мобильном устройстве.

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#38]
Android 7.1 --> веб версия
Процесс: аунтентификация - ошибка сервера
При попытке входа на веб версию сайта с учетными данными агента, который зарегестрировался на мобильном устройстве, возникает ошибка сервера (статус 500).
![2018-01-15_175908](https://user-images.githubusercontent.com/30126152/34951127-e66db414-fa1d-11e7-8741-eda49bae118e.jpg)
![2018-01-15_175937](https://user-images.githubusercontent.com/30126152/34951130-e9b5fbfe-fa1d-11e7-8e0f-92685373d7e0.jpg)

**Comment by strannik-mas** [comment]
Проблема касается хрома
Версия 63.0.3239.132 (Официальная сборка), (64 бит)

**Comment by konstcos** [comment]
Проблему так и не нашли.
После включения дебагера начал нормально входить.
У меня на хроме (и других браузера) все работало нормально.
