### ISSUE TITLE
Страница перестает реагировать.

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#42]
Андроид 7.1, роль: любая
Процесс: регистрация
При переходе экрана в режим Sleep (либо просто после простоя) и возвращении страница перестаёт реагировать на клики - не работают ни кнопки ни чекбоксы, помогает перезагрузка приложения.
![virtualbox_android 7 1_16_01_2018_10_18_53](https://user-images.githubusercontent.com/30126152/34978636-8277c708-faa7-11e7-8431-8eea2ba97789.png)

**Comment by strannik-mas** [comment]
причем почему-то при открытии возвращается на шаг назад, т.е. в данном случае на экран выбора роли.

**Comment by strannik-mas** [comment]
в Android 6 тоже самое

**Comment by konstcos** [comment]
На телефоне нормально отрабатывает. Возможно, это проблема эмулятора.

**Comment by VyacheslavZemko** [comment]
У меня на версии андроида 7.0 воспроизвести этот баг не удалось.

**Comment by konstcos** [comment]
Samsung Galaxy S200
android 5.1
все работает нормально при любых действиях (выключени, сворачивание... )
