### ISSUE TITLE
Нельзя зарегестрироваться под любым email адресом

### ISSUE THREAD

**Issue by strannik-mas** [konstcos/contact#51]
Андроид 7.1
Процесс: регистрация агента - ввод email/password
теперь валидация проходит, но форма не отправляется - после нажатия на кнопку остаёмся на той же странице. мэйлы : test_12@amail.club
test_12@mail2.space
![34950738-b3ef963e-fa1c-11e7-8dff-2233d97f8a04](https://user-images.githubusercontent.com/30126152/34994979-d5835760-fadd-11e7-9d58-803f70b5a910.png)

**Comment by konstcos** [comment]
Сейчас регистрация должна проходить нормально
